const COUNTER = {
  ADD: "COUNTER_ADD",
  RESET: "COUNTER_RESET"
};

const MOVIES = {
  LOAD: "MOVIES_LOAD",
  LOAD_SUCCESS: "MOVIES_LOAD_SUCCESS",
  LOAD_FAIL: "MOVIES_LOAD_FAIL"
};

const STATS = {
  LOAD: "STATS_LOAD",
  LOAD_SUCCESS: "STATS_LOAD_SUCCESS",
  LOAD_FAIL: "STATS_LOAD_FAIL"
};

export { COUNTER, MOVIES, STATS };
